require 'open-uri'
require 'date'
require 'cgi'
require 'rubygems'
require 'hpricot'
require 'chronic'

require File.dirname(__FILE__) + '/imdb/imdb_search'
require File.dirname(__FILE__) + '/imdb/imdb_movie'
require File.dirname(__FILE__) + '/string_extensions'